import type { LucideIcon } from 'lucide-react'
import {
  ArrowUpDown,
  AtSign,
  Building2,
  Calendar,
  CircleMinus,
  Combine,
  Equal,
  Globe,
  Hash,
  Heading,
  Heart,
  Image as ImageIcon,
  Layers,
  LayoutGrid,
  List,
  MessagesSquare,
  MessageSquareOff,
  Palette,
  Quote,
  Radio,
  Repeat2,
  Reply,
  ScanSearch,
  Search,
  Shapes,
  ShieldAlert,
  Sparkles,
  Star,
  User,
  Users,
  UserX,
  Video,
} from 'lucide-react'
import type { ConceptId } from '@apricot-cake/dialect-core'

/**
 * 各条件の先頭に出す性質アイコン。core/conceptDefs はフレームワーク非依存に保ちたい
 * ので、Lucideコンポーネントとの対応表はUI層のここに置く。以前は手書きのSVGパスを
 * 使っていたが字形が歪む(星など)ため、本物のLucideに統一した。
 */
export const CONCEPT_ICONS: Record<ConceptId, LucideIcon> = {
  keywords: Search,
  exactPhrase: Quote,
  keywordsOr: Combine,
  exclude: CircleMinus,
  fromUser: User,
  excludeUser: UserX,
  toUser: Reply,
  mentionsUser: AtSign,
  excludeMentions: AtSign,
  exactMatchMode: ScanSearch,
  xList: List,
  hashtag: Hash,
  hashtagOr: Hash,
  excludeHashtag: CircleMinus,
  period: Calendar,
  titleOnly: Heading,
  mediaOnly: ImageIcon,
  videoOnly: Video,
  exactTag: Equal,
  tagTitleCaption: Layers,
  workType: Palette,
  resultType: Video,
  language: Globe,
  sortOrder: ArrowUpDown,
  excludeReplies: MessageSquareOff,
  repliesOnly: Reply,
  liveOnly: Radio,
  minLikes: Heart,
  minReposts: Repeat2,
  minReplies: MessagesSquare,
  genre: Shapes,
  nicoKind: Building2,
  fantiaCategory: LayoutGrid,
  fantiaAudience: Users,
  safeSearchOff: ShieldAlert,
  pixivPopular: Star,
  ageRating: ShieldAlert,
  excludeAi: Sparkles,
}
