import type { LucideIcon } from 'lucide-react'
import {
  ArrowUpDown,
  AtSign,
  BadgeCheck,
  BadgeJapaneseYen,
  Building2,
  Calendar,
  Captions,
  CircleMinus,
  Clock,
  Combine,
  Contrast,
  Copyright,
  Cuboid,
  Equal,
  Gem,
  Glasses,
  Globe,
  Hash,
  Heading,
  Heart,
  Image as ImageIcon,
  Layers,
  LayoutGrid,
  Link,
  Link2,
  List,
  MapPin,
  MessagesSquare,
  MessageSquare,
  MessageSquareOff,
  Monitor,
  Orbit,
  Palette,
  Quote,
  Radio,
  Repeat2,
  Reply,
  Search,
  Shapes,
  ShieldAlert,
  ShoppingBag,
  Sparkles,
  Star,
  User,
  Users,
  UserX,
  Video,
} from 'lucide-react'
import type { ConceptId } from '@/core/types'

/**
 * 各条件の先頭に出す性質アイコン。core/conceptDefs はフレームワーク非依存に保ちたい
 * ので、Lucideコンポーネントとの対応表はUI層のここに置く。以前は手書きのSVGパスを
 * 使っていたが字形が歪む(星など)ため、本物のLucideに統一した。
 */
export const CONCEPT_ICONS: Record<ConceptId, LucideIcon> = {
  keywords: Search,
  exactPhrase: Quote,
  keywordsOr: Combine,
  exclude: CircleMinus,
  fromUser: User,
  excludeUser: UserX,
  toUser: Reply,
  mentionsUser: AtSign,
  subreddit: MessageSquare,
  domain: Link2,
  xList: List,
  hashtag: Hash,
  period: Calendar,
  titleOnly: Heading,
  mediaOnly: ImageIcon,
  exactTag: Equal,
  tagTitleCaption: Layers,
  videoLength: Clock,
  workType: Palette,
  resultType: Video,
  language: Globe,
  sortOrder: ArrowUpDown,
  linksOnly: Link,
  verifiedOnly: BadgeCheck,
  excludeReplies: MessageSquareOff,
  liveOnly: Radio,
  fourK: Gem,
  hdOnly: Monitor,
  captionsOnly: Captions,
  creativeCommons: Copyright,
  threeSixty: Orbit,
  vr180: Glasses,
  threeD: Cuboid,
  hdr: Contrast,
  locationOnly: MapPin,
  purchased: ShoppingBag,
  minLikes: Heart,
  minReposts: Repeat2,
  minReplies: MessagesSquare,
  genre: Shapes,
  nicoKind: Building2,
  paidOnly: BadgeJapaneseYen,
  fantiaCategory: LayoutGrid,
  fantiaAudience: Users,
  safeSearchOff: ShieldAlert,
  pixivPopular: Star,
  ageRating: ShieldAlert,
  excludeAi: Sparkles,
}
