import type { MessageKey } from '@/i18n'
import type { ConceptId, ConceptSupport, PlatformDef, QueryState } from './types'
import { supportOf } from './types'
import { PLATFORMS } from './platforms'

/** 統一条件バーに載るウィジェットの種類 */
export type WidgetKind = 'chips' | 'plain' | 'toggle' | 'select' | 'sort' | 'period'

export interface ConceptDef {
  id: ConceptId
  /** 値を持つ QueryState のフィールド。period系はsince側の2値を持つため代表してsince側 */
  field: keyof QueryState
  widget: WidgetKind
  /** phraseを持つ2つ目のフィールド(until側)。period系のみ。省略時は'until'(既存periodの既定) */
  untilField?: keyof QueryState
  /** chips: 入力全体を1語として扱う(スペースを含む語句を保つ)。省略時は語ごとに分割 */
  phrase?: boolean
  inputType?: 'number'
  labelKey: MessageKey
  helpKey: MessageKey
  placeholderKey?: MessageKey
}

/** 新UIの条件メタデータ。並び順はピッカーの同数タイブレークに使う(デザイン準拠) */
export const CONCEPT_DEFS: ConceptDef[] = [
  {
    id: 'keywords',
    field: 'terms',
    widget: 'chips',
    phrase: true,
    labelKey: 'concept.keywords.label',
    helpKey: 'concept.keywords.help',
    placeholderKey: 'concept.keywords.placeholder',
  },
  {
    id: 'exactPhrase',
    field: 'exactPhrase',
    widget: 'chips',
    phrase: true,
    labelKey: 'concept.exactPhrase.label',
    helpKey: 'concept.exactPhrase.help',
    placeholderKey: 'concept.exactPhrase.placeholder',
  },
  {
    id: 'keywordsOr',
    field: 'keywordsOr',
    widget: 'chips',
    labelKey: 'concept.keywordsOr.label',
    helpKey: 'concept.keywordsOr.help',
    placeholderKey: 'concept.keywordsOr.placeholder',
  },
  {
    id: 'exclude',
    field: 'exclude',
    widget: 'chips',
    labelKey: 'concept.exclude.label',
    helpKey: 'concept.exclude.help',
    placeholderKey: 'concept.exclude.placeholder',
  },
  {
    id: 'fromUser',
    field: 'fromUser',
    widget: 'plain',
    labelKey: 'concept.fromUser.label',
    helpKey: 'concept.fromUser.help',
    placeholderKey: 'concept.fromUser.placeholder',
  },
  {
    id: 'hashtag',
    field: 'hashtag',
    widget: 'chips',
    labelKey: 'concept.hashtag.label',
    helpKey: 'concept.hashtag.help',
    placeholderKey: 'concept.hashtag.placeholder',
  },
  {
    id: 'hashtagOr',
    field: 'hashtagOr',
    widget: 'chips',
    labelKey: 'concept.hashtagOr.label',
    helpKey: 'concept.hashtagOr.help',
    placeholderKey: 'concept.hashtagOr.placeholder',
  },
  {
    id: 'excludeHashtag',
    field: 'excludeHashtag',
    widget: 'chips',
    labelKey: 'concept.excludeHashtag.label',
    helpKey: 'concept.excludeHashtag.help',
    placeholderKey: 'concept.excludeHashtag.placeholder',
  },
  {
    id: 'period',
    field: 'since',
    widget: 'period',
    labelKey: 'concept.period.label',
    helpKey: 'concept.period.help',
  },
  {
    id: 'titleOnly',
    field: 'titleOnly',
    widget: 'toggle',
    labelKey: 'concept.titleOnly.label',
    helpKey: 'concept.titleOnly.help',
  },
  {
    id: 'exactTag',
    field: 'exactTag',
    widget: 'toggle',
    labelKey: 'concept.exactTag.label',
    helpKey: 'concept.exactTag.help',
  },
  {
    id: 'tagTitleCaption',
    field: 'tagTitleCaption',
    widget: 'toggle',
    labelKey: 'concept.tagTitleCaption.label',
    helpKey: 'concept.tagTitleCaption.help',
  },
  {
    id: 'mediaOnly',
    field: 'mediaOnly',
    widget: 'toggle',
    labelKey: 'concept.mediaOnly.label',
    helpKey: 'concept.mediaOnly.help',
  },
  {
    id: 'videoOnly',
    field: 'videoOnly',
    widget: 'toggle',
    labelKey: 'concept.videoOnly.label',
    helpKey: 'concept.videoOnly.help',
  },
  {
    id: 'repliesOnly',
    field: 'repliesOnly',
    widget: 'toggle',
    labelKey: 'concept.repliesOnly.label',
    helpKey: 'concept.repliesOnly.help',
  },
  {
    id: 'followingOnly',
    field: 'followingOnly',
    widget: 'toggle',
    labelKey: 'concept.followingOnly.label',
    helpKey: 'concept.followingOnly.help',
  },
  {
    id: 'liveOnly',
    field: 'liveOnly',
    widget: 'toggle',
    labelKey: 'concept.liveOnly.label',
    helpKey: 'concept.liveOnly.help',
  },
  {
    id: 'fourK',
    field: 'fourK',
    widget: 'toggle',
    labelKey: 'concept.fourK.label',
    helpKey: 'concept.fourK.help',
  },
  {
    id: 'hdOnly',
    field: 'hdOnly',
    widget: 'toggle',
    labelKey: 'concept.hdOnly.label',
    helpKey: 'concept.hdOnly.help',
  },
  {
    id: 'captionsOnly',
    field: 'captionsOnly',
    widget: 'toggle',
    labelKey: 'concept.captionsOnly.label',
    helpKey: 'concept.captionsOnly.help',
  },
  {
    id: 'creativeCommons',
    field: 'creativeCommons',
    widget: 'toggle',
    labelKey: 'concept.creativeCommons.label',
    helpKey: 'concept.creativeCommons.help',
  },
  {
    id: 'threeSixty',
    field: 'threeSixty',
    widget: 'toggle',
    labelKey: 'concept.threeSixty.label',
    helpKey: 'concept.threeSixty.help',
  },
  {
    id: 'vr180',
    field: 'vr180',
    widget: 'toggle',
    labelKey: 'concept.vr180.label',
    helpKey: 'concept.vr180.help',
  },
  {
    id: 'threeD',
    field: 'threeD',
    widget: 'toggle',
    labelKey: 'concept.threeD.label',
    helpKey: 'concept.threeD.help',
  },
  {
    id: 'hdr',
    field: 'hdr',
    widget: 'toggle',
    labelKey: 'concept.hdr.label',
    helpKey: 'concept.hdr.help',
  },
  {
    id: 'locationOnly',
    field: 'locationOnly',
    widget: 'toggle',
    labelKey: 'concept.locationOnly.label',
    helpKey: 'concept.locationOnly.help',
  },
  {
    id: 'purchased',
    field: 'purchased',
    widget: 'toggle',
    labelKey: 'concept.purchased.label',
    helpKey: 'concept.purchased.help',
  },
  {
    id: 'videoLength',
    field: 'videoLength',
    widget: 'select',
    labelKey: 'concept.videoLength.label',
    helpKey: 'concept.videoLength.help',
  },
  {
    id: 'workType',
    field: 'workType',
    widget: 'select',
    labelKey: 'concept.workType.label',
    helpKey: 'concept.workType.help',
  },
  {
    id: 'genre',
    field: 'genre',
    widget: 'select',
    labelKey: 'concept.genre.label',
    helpKey: 'concept.genre.help',
  },
  {
    id: 'nicoKind',
    field: 'nicoKind',
    widget: 'select',
    labelKey: 'concept.nicoKind.label',
    helpKey: 'concept.nicoKind.help',
  },
  {
    id: 'paidOnly',
    field: 'paidOnly',
    widget: 'toggle',
    labelKey: 'concept.paidOnly.label',
    helpKey: 'concept.paidOnly.help',
  },
  {
    id: 'fantiaCategory',
    field: 'fantiaCategory',
    widget: 'select',
    labelKey: 'concept.fantiaCategory.label',
    helpKey: 'concept.fantiaCategory.help',
  },
  {
    id: 'fantiaAudience',
    field: 'fantiaAudience',
    widget: 'select',
    labelKey: 'concept.fantiaAudience.label',
    helpKey: 'concept.fantiaAudience.help',
  },
  {
    id: 'safeSearchOff',
    field: 'safeSearchOff',
    widget: 'toggle',
    labelKey: 'concept.safeSearchOff.label',
    helpKey: 'concept.safeSearchOff.help',
  },
  {
    id: 'pixivPopular',
    field: 'pixivPopular',
    widget: 'select',
    labelKey: 'concept.pixivPopular.label',
    helpKey: 'concept.pixivPopular.help',
  },
  {
    id: 'ageRating',
    field: 'ageRating',
    widget: 'select',
    labelKey: 'concept.ageRating.label',
    helpKey: 'concept.ageRating.help',
  },
  {
    id: 'excludeAi',
    field: 'excludeAi',
    widget: 'toggle',
    labelKey: 'concept.excludeAi.label',
    helpKey: 'concept.excludeAi.help',
  },
  {
    id: 'resultType',
    field: 'resultType',
    widget: 'select',
    labelKey: 'concept.resultType.label',
    helpKey: 'concept.resultType.help',
  },
  {
    id: 'language',
    field: 'language',
    widget: 'select',
    labelKey: 'concept.language.label',
    helpKey: 'concept.language.help',
  },
  {
    id: 'sortOrder',
    field: 'sort',
    widget: 'sort',
    labelKey: 'concept.sortOrder.label',
    helpKey: 'concept.sortOrder.help',
  },
  {
    id: 'toUser',
    field: 'toUser',
    widget: 'chips',
    labelKey: 'concept.toUser.label',
    helpKey: 'concept.toUser.help',
    placeholderKey: 'concept.toUser.placeholder',
  },
  {
    id: 'excludeUser',
    field: 'excludeUser',
    widget: 'chips',
    labelKey: 'concept.excludeUser.label',
    helpKey: 'concept.excludeUser.help',
    placeholderKey: 'concept.excludeUser.placeholder',
  },
  {
    id: 'minLikes',
    field: 'minLikes',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minLikes.label',
    helpKey: 'concept.minLikes.help',
    placeholderKey: 'concept.minLikes.placeholder',
  },
  {
    id: 'minReposts',
    field: 'minReposts',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minReposts.label',
    helpKey: 'concept.minReposts.help',
    placeholderKey: 'concept.minReposts.placeholder',
  },
  {
    id: 'minReplies',
    field: 'minReplies',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minReplies.label',
    helpKey: 'concept.minReplies.help',
    placeholderKey: 'concept.minReplies.placeholder',
  },
  {
    id: 'excludeReplies',
    field: 'excludeReplies',
    widget: 'toggle',
    labelKey: 'concept.excludeReplies.label',
    helpKey: 'concept.excludeReplies.help',
  },
  {
    id: 'linksOnly',
    field: 'linksOnly',
    widget: 'toggle',
    labelKey: 'concept.linksOnly.label',
    helpKey: 'concept.linksOnly.help',
  },
  {
    id: 'verifiedOnly',
    field: 'verifiedOnly',
    widget: 'toggle',
    labelKey: 'concept.verifiedOnly.label',
    helpKey: 'concept.verifiedOnly.help',
  },
  {
    id: 'mentionsUser',
    field: 'mentionsUser',
    widget: 'plain',
    labelKey: 'concept.mentionsUser.label',
    helpKey: 'concept.mentionsUser.help',
    placeholderKey: 'concept.mentionsUser.placeholder',
  },
  {
    id: 'excludeMentions',
    field: 'excludeMentions',
    widget: 'plain',
    labelKey: 'concept.excludeMentions.label',
    helpKey: 'concept.excludeMentions.help',
    placeholderKey: 'concept.excludeMentions.placeholder',
  },
  {
    id: 'domain',
    field: 'domain',
    widget: 'plain',
    labelKey: 'concept.domain.label',
    helpKey: 'concept.domain.help',
    placeholderKey: 'concept.domain.placeholder',
  },
  {
    id: 'excludeDomain',
    field: 'excludeDomain',
    widget: 'plain',
    labelKey: 'concept.excludeDomain.label',
    helpKey: 'concept.excludeDomain.help',
    placeholderKey: 'concept.excludeDomain.placeholder',
  },
  {
    id: 'linkUrl',
    field: 'linkUrl',
    widget: 'plain',
    labelKey: 'concept.linkUrl.label',
    helpKey: 'concept.linkUrl.help',
    placeholderKey: 'concept.linkUrl.placeholder',
  },
  {
    id: 'excludeLinkUrl',
    field: 'excludeLinkUrl',
    widget: 'plain',
    labelKey: 'concept.excludeLinkUrl.label',
    helpKey: 'concept.excludeLinkUrl.help',
    placeholderKey: 'concept.excludeLinkUrl.placeholder',
  },
  {
    id: 'xList',
    field: 'xList',
    widget: 'plain',
    labelKey: 'concept.xList.label',
    helpKey: 'concept.xList.help',
    placeholderKey: 'concept.xList.placeholder',
  },
  {
    id: 'fileType',
    field: 'fileType',
    widget: 'select',
    labelKey: 'concept.fileType.label',
    helpKey: 'concept.fileType.help',
  },
  {
    id: 'region',
    field: 'region',
    widget: 'plain',
    labelKey: 'concept.region.label',
    helpKey: 'concept.region.help',
    placeholderKey: 'concept.region.placeholder',
  },
  {
    id: 'license',
    field: 'license',
    widget: 'select',
    labelKey: 'concept.license.label',
    helpKey: 'concept.license.help',
  },
  {
    id: 'exactMatchMode',
    field: 'exactMatchMode',
    widget: 'toggle',
    labelKey: 'concept.exactMatchMode.label',
    helpKey: 'concept.exactMatchMode.help',
  },
  {
    id: 'codeLanguage',
    field: 'codeLanguage',
    widget: 'plain',
    labelKey: 'concept.codeLanguage.label',
    helpKey: 'concept.codeLanguage.help',
    placeholderKey: 'concept.codeLanguage.placeholder',
  },
  {
    id: 'minStars',
    field: 'minStars',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minStars.label',
    helpKey: 'concept.minStars.help',
    placeholderKey: 'concept.minStars.placeholder',
  },
  {
    id: 'minStocks',
    field: 'minStocks',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minStocks.label',
    helpKey: 'concept.minStocks.help',
    placeholderKey: 'concept.minStocks.placeholder',
  },
  {
    id: 'semanticSearch',
    field: 'semanticSearch',
    widget: 'toggle',
    labelKey: 'concept.semanticSearch.label',
    helpKey: 'concept.semanticSearch.help',
  },
  {
    id: 'subreddit',
    field: 'subreddit',
    widget: 'chips',
    labelKey: 'concept.subreddit.label',
    helpKey: 'concept.subreddit.help',
    placeholderKey: 'concept.subreddit.placeholder',
  },
  {
    id: 'minForks',
    field: 'minForks',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minForks.label',
    helpKey: 'concept.minForks.help',
    placeholderKey: 'concept.minForks.placeholder',
  },
  {
    id: 'minSizeKb',
    field: 'minSizeKb',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minSizeKb.label',
    helpKey: 'concept.minSizeKb.help',
    placeholderKey: 'concept.minSizeKb.placeholder',
  },
  {
    id: 'pushedPeriod',
    field: 'pushedSince',
    untilField: 'pushedUntil',
    widget: 'period',
    labelKey: 'concept.pushedPeriod.label',
    helpKey: 'concept.pushedPeriod.help',
  },
  {
    id: 'codeLicense',
    field: 'codeLicense',
    widget: 'select',
    labelKey: 'concept.codeLicense.label',
    helpKey: 'concept.codeLicense.help',
  },
  {
    id: 'includeForks',
    field: 'includeForks',
    widget: 'select',
    labelKey: 'concept.includeForks.label',
    helpKey: 'concept.includeForks.help',
  },
  {
    id: 'visibility',
    field: 'visibility',
    widget: 'select',
    labelKey: 'concept.visibility.label',
    helpKey: 'concept.visibility.help',
  },
  {
    id: 'topic',
    field: 'topic',
    widget: 'chips',
    labelKey: 'concept.topic.label',
    helpKey: 'concept.topic.help',
    placeholderKey: 'concept.topic.placeholder',
  },
  {
    id: 'searchInName',
    field: 'searchInName',
    widget: 'toggle',
    labelKey: 'concept.searchInName.label',
    helpKey: 'concept.searchInName.help',
  },
  {
    id: 'searchInDescription',
    field: 'searchInDescription',
    widget: 'toggle',
    labelKey: 'concept.searchInDescription.label',
    helpKey: 'concept.searchInDescription.help',
  },
  {
    id: 'searchInReadme',
    field: 'searchInReadme',
    widget: 'toggle',
    labelKey: 'concept.searchInReadme.label',
    helpKey: 'concept.searchInReadme.help',
  },
  {
    id: 'archived',
    field: 'archived',
    widget: 'select',
    labelKey: 'concept.archived.label',
    helpKey: 'concept.archived.help',
  },
  {
    id: 'mirror',
    field: 'mirror',
    widget: 'select',
    labelKey: 'concept.mirror.label',
    helpKey: 'concept.mirror.help',
  },
  {
    id: 'org',
    field: 'org',
    widget: 'plain',
    labelKey: 'concept.org.label',
    helpKey: 'concept.org.help',
    placeholderKey: 'concept.org.placeholder',
  },
  {
    id: 'fileExtension',
    field: 'fileExtension',
    widget: 'plain',
    labelKey: 'concept.fileExtension.label',
    helpKey: 'concept.fileExtension.help',
    placeholderKey: 'concept.fileExtension.placeholder',
  },
  {
    id: 'filePath',
    field: 'filePath',
    widget: 'plain',
    labelKey: 'concept.filePath.label',
    helpKey: 'concept.filePath.help',
    placeholderKey: 'concept.filePath.placeholder',
  },
  {
    id: 'fileName',
    field: 'fileName',
    widget: 'plain',
    labelKey: 'concept.fileName.label',
    helpKey: 'concept.fileName.help',
    placeholderKey: 'concept.fileName.placeholder',
  },
  {
    id: 'issueState',
    field: 'issueState',
    widget: 'select',
    labelKey: 'concept.issueState.label',
    helpKey: 'concept.issueState.help',
  },
  {
    id: 'issueReason',
    field: 'issueReason',
    widget: 'select',
    labelKey: 'concept.issueReason.label',
    helpKey: 'concept.issueReason.help',
  },
  {
    id: 'minComments',
    field: 'minComments',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minComments.label',
    helpKey: 'concept.minComments.help',
    placeholderKey: 'concept.minComments.placeholder',
  },
  {
    id: 'label',
    field: 'label',
    widget: 'chips',
    labelKey: 'concept.label.label',
    helpKey: 'concept.label.help',
    placeholderKey: 'concept.label.placeholder',
  },
  {
    id: 'assignee',
    field: 'assignee',
    widget: 'chips',
    labelKey: 'concept.assignee.label',
    helpKey: 'concept.assignee.help',
    placeholderKey: 'concept.assignee.placeholder',
  },
  {
    id: 'updatedPeriod',
    field: 'updatedSince',
    untilField: 'updatedUntil',
    widget: 'period',
    labelKey: 'concept.updatedPeriod.label',
    helpKey: 'concept.updatedPeriod.help',
  },
  {
    id: 'fullName',
    field: 'fullName',
    widget: 'plain',
    labelKey: 'concept.fullName.label',
    helpKey: 'concept.fullName.help',
    placeholderKey: 'concept.fullName.placeholder',
  },
  {
    id: 'userLocation',
    field: 'userLocation',
    widget: 'plain',
    labelKey: 'concept.userLocation.label',
    helpKey: 'concept.userLocation.help',
    placeholderKey: 'concept.userLocation.placeholder',
  },
  {
    id: 'minFollowers',
    field: 'minFollowers',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minFollowers.label',
    helpKey: 'concept.minFollowers.help',
    placeholderKey: 'concept.minFollowers.placeholder',
  },
  {
    id: 'minRepos',
    field: 'minRepos',
    widget: 'plain',
    inputType: 'number',
    labelKey: 'concept.minRepos.label',
    helpKey: 'concept.minRepos.help',
    placeholderKey: 'concept.minRepos.placeholder',
  },
]

export const CONCEPT_MAP = Object.fromEntries(CONCEPT_DEFS.map((d) => [d.id, d])) as Record<
  ConceptId,
  ConceptDef
>

/**
 * 静的に対応しているサイト。support に明示的な none エントリを持つサイトが
 * あるため、記載の有無ではなく level で除外する(対応数の水増し防止)
 */
export function supportersOf(concept: ConceptId): PlatformDef[] {
  return PLATFORMS.filter((p) => supportOf(p, concept).level !== 'none')
}

/** 対応サイト数(静的)。ピッカーの並び順に使う */
export const SUPPORT_COUNT = Object.fromEntries(
  CONCEPT_DEFS.map((d) => [d.id, supportersOf(d.id).length]),
) as Record<ConceptId, number>

/** 現在の入力まで踏まえた実効レベル(dynamicSupport を静的 support に重ねる) */
export function effectiveLevel(
  platform: PlatformDef,
  concept: ConceptId,
  state: QueryState,
): ConceptSupport {
  const dyn = platform.dynamicSupport?.(state)
  return dyn?.[concept] ?? supportOf(platform, concept)
}

/**
 * 現在の入力まで踏まえた実対応サイト。選んだ値によって dynamicSupport で落ちるサイト
 * (急上昇を持たないサイト等)を除いて数える。「対応 N」バッジと選択肢ごとの対応数に使う
 */
export function activeSupportersOf(concept: ConceptId, state: QueryState): PlatformDef[] {
  return supportersOf(concept).filter((p) => effectiveLevel(p, concept, state).level !== 'none')
}

/**
 * 対応ポップオーバー用: 対応サイトを「完全」と「それ以外(一部・今の入力では不可)」に
 * 振り分ける。入力次第で none に落ちたサイトも「一部対応」側に出す(デザイン準拠)
 */
export function splitSupporters(
  concept: ConceptId,
  state: QueryState,
): { full: PlatformDef[]; partial: PlatformDef[] } {
  const full: PlatformDef[] = []
  const partial: PlatformDef[] = []
  for (const p of supportersOf(concept)) {
    if (effectiveLevel(p, concept, state).level === 'full') full.push(p)
    else partial.push(p)
  }
  return { full, partial }
}

export interface SelectOption {
  value: string
  labelKey: MessageKey
}

/** セレクト式の条件の選択肢。値は QueryState の各フィールドの値と対応する */
export const SELECT_OPTIONS: Partial<Record<ConceptId, SelectOption[]>> = {
  videoLength: [
    { value: '', labelKey: 'concept.videoLength.none' },
    { value: 'short', labelKey: 'concept.videoLength.short' },
    { value: 'medium', labelKey: 'concept.videoLength.medium' },
    { value: 'long', labelKey: 'concept.videoLength.long' },
  ],
  workType: [
    { value: '', labelKey: 'concept.workType.none' },
    { value: 'illust', labelKey: 'concept.workType.illust' },
    { value: 'manga', labelKey: 'concept.workType.manga' },
    { value: 'ugoira', labelKey: 'concept.workType.ugoira' },
    { value: 'novel', labelKey: 'concept.workType.novel' },
  ],
  resultType: [
    { value: '', labelKey: 'concept.resultType.none' },
    { value: 'video', labelKey: 'concept.resultType.video' },
    { value: 'short', labelKey: 'concept.resultType.short' },
    { value: 'channel', labelKey: 'concept.resultType.channel' },
    { value: 'playlist', labelKey: 'concept.resultType.playlist' },
    { value: 'posts', labelKey: 'concept.resultType.posts' },
    { value: 'communities', labelKey: 'concept.resultType.communities' },
    { value: 'comments', labelKey: 'concept.resultType.comments' },
    { value: 'media', labelKey: 'concept.resultType.media' },
    { value: 'people', labelKey: 'concept.resultType.people' },
    { value: 'board', labelKey: 'concept.resultType.board' },
    { value: 'bangumi', labelKey: 'concept.resultType.bangumi' },
    { value: 'pgc', labelKey: 'concept.resultType.pgc' },
    { value: 'live', labelKey: 'concept.resultType.live' },
    { value: 'article', labelKey: 'concept.resultType.article' },
    { value: 'series', labelKey: 'concept.resultType.series' },
    { value: 'circle', labelKey: 'concept.resultType.circle' },
    { value: 'images', labelKey: 'concept.resultType.images' },
    { value: 'shopping', labelKey: 'concept.resultType.shopping' },
    { value: 'news', labelKey: 'concept.resultType.news' },
    { value: 'web', labelKey: 'concept.resultType.web' },
    { value: 'books', labelKey: 'concept.resultType.books' },
    { value: 'repositories', labelKey: 'concept.resultType.repositories' },
    { value: 'code', labelKey: 'concept.resultType.code' },
    { value: 'issues', labelKey: 'concept.resultType.issues' },
    { value: 'pullRequests', labelKey: 'concept.resultType.pullRequests' },
    { value: 'discussions', labelKey: 'concept.resultType.discussions' },
    { value: 'questions', labelKey: 'concept.resultType.questions' },
    { value: 'scraps', labelKey: 'concept.resultType.scraps' },
    { value: 'publications', labelKey: 'concept.resultType.publications' },
  ],
  language: [
    { value: '', labelKey: 'concept.language.none' },
    { value: 'ja', labelKey: 'concept.language.ja' },
    { value: 'en', labelKey: 'concept.language.en' },
    { value: 'zh', labelKey: 'concept.language.zh' },
    { value: 'ko', labelKey: 'concept.language.ko' },
    { value: 'es', labelKey: 'concept.language.es' },
    { value: 'fr', labelKey: 'concept.language.fr' },
    { value: 'de', labelKey: 'concept.language.de' },
    { value: 'pt', labelKey: 'concept.language.pt' },
    { value: 'ru', labelKey: 'concept.language.ru' },
    { value: 'it', labelKey: 'concept.language.it' },
    { value: 'ar', labelKey: 'concept.language.ar' },
    { value: 'hi', labelKey: 'concept.language.hi' },
    { value: 'th', labelKey: 'concept.language.th' },
    { value: 'id', labelKey: 'concept.language.id' },
  ],
  pixivPopular: [
    { value: '', labelKey: 'concept.pixivPopular.none' },
    { value: '00users', labelKey: 'concept.pixivPopular.100' },
    { value: '000users', labelKey: 'concept.pixivPopular.1000' },
    { value: '0000users', labelKey: 'concept.pixivPopular.10000' },
  ],
  ageRating: [
    { value: '', labelKey: 'concept.ageRating.none' },
    { value: 'safe', labelKey: 'concept.ageRating.safe' },
    { value: 'r18', labelKey: 'concept.ageRating.r18' },
  ],
  genre: [
    { value: '', labelKey: 'concept.genre.none' },
    { value: 'game', labelKey: 'concept.genre.game' },
    { value: 'animal', labelKey: 'concept.genre.animal' },
    { value: 'music_sound', labelKey: 'concept.genre.music_sound' },
    { value: 'entertainment', labelKey: 'concept.genre.entertainment' },
    { value: 'other', labelKey: 'concept.genre.other' },
    { value: 'anime', labelKey: 'concept.genre.anime' },
    { value: 'dance', labelKey: 'concept.genre.dance' },
    { value: 'radio', labelKey: 'concept.genre.radio' },
    { value: 'traveling_outdoor', labelKey: 'concept.genre.traveling_outdoor' },
    { value: 'commentary_lecture', labelKey: 'concept.genre.commentary_lecture' },
    { value: 'cooking', labelKey: 'concept.genre.cooking' },
    { value: 'technology_craft', labelKey: 'concept.genre.technology_craft' },
    { value: 'vehicle', labelKey: 'concept.genre.vehicle' },
    { value: 'nature', labelKey: 'concept.genre.nature' },
    { value: 'society_politics_news', labelKey: 'concept.genre.society_politics_news' },
    { value: 'sports', labelKey: 'concept.genre.sports' },
    { value: 'r18', labelKey: 'concept.genre.r18' },
  ],
  nicoKind: [
    { value: '', labelKey: 'concept.nicoKind.none' },
    { value: 'user', labelKey: 'concept.nicoKind.user' },
    { value: 'channel', labelKey: 'concept.nicoKind.channel' },
  ],
  fantiaCategory: [
    { value: '', labelKey: 'concept.fantiaCategory.none' },
    { value: 'illust', labelKey: 'concept.fantiaCategory.illust' },
    { value: 'comic', labelKey: 'concept.fantiaCategory.comic' },
    { value: 'vtuber', labelKey: 'concept.fantiaCategory.vtuber' },
    { value: 'voice', labelKey: 'concept.fantiaCategory.voice' },
    { value: 'voiceactor', labelKey: 'concept.fantiaCategory.voiceactor' },
    { value: '3d', labelKey: 'concept.fantiaCategory.3d' },
    { value: '2d_anime', labelKey: 'concept.fantiaCategory.2d_anime' },
    { value: 'game', labelKey: 'concept.fantiaCategory.game' },
    { value: 'music', labelKey: 'concept.fantiaCategory.music' },
    { value: 'novel', labelKey: 'concept.fantiaCategory.novel' },
    { value: 'doll', labelKey: 'concept.fantiaCategory.doll' },
    { value: 'art', labelKey: 'concept.fantiaCategory.art' },
    { value: 'program', labelKey: 'concept.fantiaCategory.program' },
    { value: 'handmade', labelKey: 'concept.fantiaCategory.handmade' },
    { value: 'history', labelKey: 'concept.fantiaCategory.history' },
    { value: 'railroad', labelKey: 'concept.fantiaCategory.railroad' },
    { value: 'shop', labelKey: 'concept.fantiaCategory.shop' },
    { value: 'other', labelKey: 'concept.fantiaCategory.other' },
    { value: 'fortune', labelKey: 'concept.fantiaCategory.fortune' },
    { value: 'cosplay', labelKey: 'concept.fantiaCategory.cosplay' },
    { value: 'idol', labelKey: 'concept.fantiaCategory.idol' },
    { value: 'youtuber', labelKey: 'concept.fantiaCategory.youtuber' },
    { value: 'photo_movie', labelKey: 'concept.fantiaCategory.photo_movie' },
    { value: 'other_real', labelKey: 'concept.fantiaCategory.other_real' },
  ],
  fantiaAudience: [
    { value: '', labelKey: 'concept.fantiaAudience.none' },
    { value: 'male', labelKey: 'concept.fantiaAudience.male' },
    { value: 'female', labelKey: 'concept.fantiaAudience.female' },
  ],
  fileType: [
    { value: '', labelKey: 'concept.fileType.none' },
    { value: 'pdf', labelKey: 'concept.fileType.pdf' },
    { value: 'ps', labelKey: 'concept.fileType.ps' },
    { value: 'dwf', labelKey: 'concept.fileType.dwf' },
    { value: 'kml', labelKey: 'concept.fileType.kml' },
    { value: 'kmz', labelKey: 'concept.fileType.kmz' },
    { value: 'xls', labelKey: 'concept.fileType.xls' },
    { value: 'ppt', labelKey: 'concept.fileType.ppt' },
    { value: 'doc', labelKey: 'concept.fileType.doc' },
    { value: 'rtf', labelKey: 'concept.fileType.rtf' },
    { value: 'swf', labelKey: 'concept.fileType.swf' },
  ],
  license: [
    { value: '', labelKey: 'concept.license.none' },
    { value: 'f', labelKey: 'concept.license.f' },
    { value: 'fc', labelKey: 'concept.license.fc' },
    { value: 'fm', labelKey: 'concept.license.fm' },
    { value: 'fmc', labelKey: 'concept.license.fmc' },
  ],
  codeLicense: [
    { value: '', labelKey: 'concept.codeLicense.none' },
    { value: '0bsd', labelKey: 'concept.codeLicense.0bsd' },
    { value: 'afl-3.0', labelKey: 'concept.codeLicense.afl-3.0' },
    { value: 'agpl-3.0', labelKey: 'concept.codeLicense.agpl-3.0' },
    { value: 'apache-2.0', labelKey: 'concept.codeLicense.apache-2.0' },
    { value: 'artistic-2.0', labelKey: 'concept.codeLicense.artistic-2.0' },
    { value: 'blueoak-1.0.0', labelKey: 'concept.codeLicense.blueoak-1.0.0' },
    { value: 'bsd-2-clause', labelKey: 'concept.codeLicense.bsd-2-clause' },
    { value: 'bsd-2-clause-patent', labelKey: 'concept.codeLicense.bsd-2-clause-patent' },
    { value: 'bsd-3-clause', labelKey: 'concept.codeLicense.bsd-3-clause' },
    { value: 'bsd-3-clause-clear', labelKey: 'concept.codeLicense.bsd-3-clause-clear' },
    { value: 'bsd-4-clause', labelKey: 'concept.codeLicense.bsd-4-clause' },
    { value: 'bsl-1.0', labelKey: 'concept.codeLicense.bsl-1.0' },
    { value: 'cc-by-4.0', labelKey: 'concept.codeLicense.cc-by-4.0' },
    { value: 'cc-by-sa-4.0', labelKey: 'concept.codeLicense.cc-by-sa-4.0' },
    { value: 'cc0-1.0', labelKey: 'concept.codeLicense.cc0-1.0' },
    { value: 'cecill-2.1', labelKey: 'concept.codeLicense.cecill-2.1' },
    { value: 'cern-ohl-p-2.0', labelKey: 'concept.codeLicense.cern-ohl-p-2.0' },
    { value: 'cern-ohl-s-2.0', labelKey: 'concept.codeLicense.cern-ohl-s-2.0' },
    { value: 'cern-ohl-w-2.0', labelKey: 'concept.codeLicense.cern-ohl-w-2.0' },
    { value: 'ecl-2.0', labelKey: 'concept.codeLicense.ecl-2.0' },
    { value: 'epl-1.0', labelKey: 'concept.codeLicense.epl-1.0' },
    { value: 'epl-2.0', labelKey: 'concept.codeLicense.epl-2.0' },
    { value: 'eupl-1.1', labelKey: 'concept.codeLicense.eupl-1.1' },
    { value: 'eupl-1.2', labelKey: 'concept.codeLicense.eupl-1.2' },
    { value: 'gfdl-1.3', labelKey: 'concept.codeLicense.gfdl-1.3' },
    { value: 'gpl-2.0', labelKey: 'concept.codeLicense.gpl-2.0' },
    { value: 'gpl-3.0', labelKey: 'concept.codeLicense.gpl-3.0' },
    { value: 'isc', labelKey: 'concept.codeLicense.isc' },
    { value: 'lgpl-2.1', labelKey: 'concept.codeLicense.lgpl-2.1' },
    { value: 'lgpl-3.0', labelKey: 'concept.codeLicense.lgpl-3.0' },
    { value: 'lppl-1.3c', labelKey: 'concept.codeLicense.lppl-1.3c' },
    { value: 'mit', labelKey: 'concept.codeLicense.mit' },
    { value: 'mit-0', labelKey: 'concept.codeLicense.mit-0' },
    { value: 'mpl-2.0', labelKey: 'concept.codeLicense.mpl-2.0' },
    { value: 'ms-pl', labelKey: 'concept.codeLicense.ms-pl' },
    { value: 'ms-rl', labelKey: 'concept.codeLicense.ms-rl' },
    { value: 'mulanpsl-2.0', labelKey: 'concept.codeLicense.mulanpsl-2.0' },
    { value: 'ncsa', labelKey: 'concept.codeLicense.ncsa' },
    { value: 'odbl-1.0', labelKey: 'concept.codeLicense.odbl-1.0' },
    { value: 'ofl-1.1', labelKey: 'concept.codeLicense.ofl-1.1' },
    { value: 'osl-3.0', labelKey: 'concept.codeLicense.osl-3.0' },
    { value: 'postgresql', labelKey: 'concept.codeLicense.postgresql' },
    { value: 'unlicense', labelKey: 'concept.codeLicense.unlicense' },
    { value: 'upl-1.0', labelKey: 'concept.codeLicense.upl-1.0' },
    { value: 'vim', labelKey: 'concept.codeLicense.vim' },
    { value: 'wtfpl', labelKey: 'concept.codeLicense.wtfpl' },
    { value: 'zlib', labelKey: 'concept.codeLicense.zlib' },
    { value: 'cc', labelKey: 'concept.codeLicense.cc' },
    { value: 'gpl', labelKey: 'concept.codeLicense.gpl' },
    { value: 'lgpl', labelKey: 'concept.codeLicense.lgpl' },
  ],
  includeForks: [
    { value: '', labelKey: 'concept.includeForks.none' },
    { value: 'true', labelKey: 'concept.includeForks.true' },
    { value: 'only', labelKey: 'concept.includeForks.only' },
  ],
  visibility: [
    { value: '', labelKey: 'concept.visibility.none' },
    { value: 'public', labelKey: 'concept.visibility.public' },
    { value: 'private', labelKey: 'concept.visibility.private' },
  ],
  archived: [
    { value: '', labelKey: 'concept.archived.none' },
    { value: 'true', labelKey: 'concept.archived.true' },
    { value: 'false', labelKey: 'concept.archived.false' },
  ],
  mirror: [
    { value: '', labelKey: 'concept.mirror.none' },
    { value: 'true', labelKey: 'concept.mirror.true' },
    { value: 'false', labelKey: 'concept.mirror.false' },
  ],
  issueState: [
    { value: '', labelKey: 'concept.issueState.none' },
    { value: 'open', labelKey: 'concept.issueState.open' },
    { value: 'closed', labelKey: 'concept.issueState.closed' },
  ],
  issueReason: [
    { value: '', labelKey: 'concept.issueReason.none' },
    { value: 'completed', labelKey: 'concept.issueReason.completed' },
    { value: 'not planned', labelKey: 'concept.issueReason.notPlanned' },
    { value: 'reopened', labelKey: 'concept.issueReason.reopened' },
  ],
}

// 「指定なし(auto)」を先頭に置くのは他のセレクト(探すものの種類など)の「指定なし」と
// 同じ作法。以降は対応サイト数の多い順(新しい順・人気順が大半、急上昇以下は少数サイト専用)
export const SORT_OPTIONS: Array<{ value: QueryState['sort']; labelKey: MessageKey }> = [
  { value: 'auto', labelKey: 'concept.sortOrder.auto' },
  { value: 'new', labelKey: 'concept.sortOrder.new' },
  { value: 'top', labelKey: 'concept.sortOrder.top' },
  { value: 'hot', labelKey: 'concept.sortOrder.hot' },
  { value: 'comments', labelKey: 'concept.sortOrder.comments' },
  { value: 'danmaku', labelKey: 'concept.sortOrder.danmaku' },
  { value: 'favorites', labelKey: 'concept.sortOrder.favorites' },
  { value: 'likes', labelKey: 'concept.sortOrder.likes' },
  { value: 'commentDate', labelKey: 'concept.sortOrder.commentDate' },
  { value: 'videoCount', labelKey: 'concept.sortOrder.videoCount' },
  { value: 'videoAdded', labelKey: 'concept.sortOrder.videoAdded' },
  { value: 'followerCount', labelKey: 'concept.sortOrder.followerCount' },
  { value: 'liveCount', labelKey: 'concept.sortOrder.liveCount' },
]
