/**
 * ja UI のピッカー内検索で「にんき→人気」のような“漢字↔かな読み”一致を効かせるための、
 * 読み辞書の生成スクリプト。漢字を含む日本語テキスト(同義語・ラベル・選択肢の値)を
 * kuromoji でカタカナ読みに変換し、src/core/readings.generated.ts へ書き出す。
 *
 * 混在形(かな＋漢字)も拾う: 「あて先」のように途中まで漢字変換したクエリを通したい。
 * kuromoji が分割する複合語(返信＋先、並び＋順…)は、トークンごとに「読み or 表層」を
 * 組み合わせた混在形を自動生成する。ただし「宛先」のように1語で読まれる熟語は割れないため、
 * その手の混在形だけ EXTRA で人手追加する。
 *
 * なぜ生成方式か: フィールドは今後増える前提なので、読みを手書きで維持したくない。
 * kuromoji が取り違える数語(例: しきい値→シキイネ)は OVERRIDES で人手上書きする
 * (自動検知はしきれない＝一度は目視が要る、というのが実測での結論)。
 *
 * 実行: npm run gen:readings
 * 生成物はコミットする。コードとズレていないかは check:readings が CI で検査する。
 */
import { writeFileSync } from 'node:fs'
import { resolve as pathResolve } from 'node:path'
import kuromoji from 'kuromoji'
import { collectReadingPhrases, hasKanji } from './readingCorpus'

type Tok = { surface_form: string; reading?: string }

/**
 * kuromoji が自信満々に取り違える語の人手上書き(かな読み)。値は空白区切りで複数可
 * (例: 板 は「いた」「ばん」両方効かせたい)。ここは目視で育てる小さなリスト。
 */
const OVERRIDES: Record<string, string> = {
  しきい値: 'シキイチ',
  語: 'ゴ',
  板: 'イタ バン',
}

/**
 * 1語として読まれ分割読みを取り出せない熟語向けの、混在(かな＋漢字)形の人手追加。
 * 例: 宛先 は kuromoji が1語(アテサキ)で読むため「あて先」を自動生成できない。
 */
const EXTRA: Record<string, string[]> = {
  宛先: ['アテ先', '宛サキ'],
}

/** 2^MAX まで混在形を展開。これを超える多漢字語は組合せ爆発を避け全かな読みのみにする */
const MAX_MIX_TOKENS = 4

function readingOf(t: Tok): string {
  return t.reading && t.reading !== '*' ? t.reading : t.surface_form
}

/** トークン列から混在形(各漢字トークンを「読み or 表層」で選んだ全組合せ)を作る */
function variantsFor(tokens: Tok[]): string[] {
  const choices = tokens.map((t) =>
    hasKanji(t.surface_form) ? [readingOf(t), t.surface_form] : [t.surface_form],
  )
  const kanjiTokens = choices.filter((c) => c.length > 1).length
  const fullReading = tokens.map(readingOf).join('')
  if (kanjiTokens > MAX_MIX_TOKENS) return [fullReading]
  let combos = ['']
  for (const opts of choices) {
    const next: string[] = []
    for (const c of combos) for (const o of opts) next.push(c + o)
    combos = next
  }
  return [...new Set(combos)]
}

kuromoji.builder({ dicPath: 'node_modules/kuromoji/dict' }).build((err, tokenizer) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }

  const phrases = collectReadingPhrases().sort((a, b) => a.localeCompare(b, 'ja'))
  const readings: Record<string, string> = {}
  const notes: string[] = []
  for (const phrase of phrases) {
    let forms: string[]
    if (OVERRIDES[phrase]) {
      forms = OVERRIDES[phrase].split(' ')
      notes.push(`${phrase} → ${OVERRIDES[phrase]} (上書き)`)
    } else if (/\s/.test(phrase)) {
      // 空白を含む値ラベルは混在展開すると語境界が壊れるので全かな読みだけにする
      forms = [tokenizer.tokenize(phrase).map(readingOf).join('')]
    } else {
      forms = variantsFor(tokenizer.tokenize(phrase))
    }
    const extra = EXTRA[phrase]
    if (extra) {
      forms = [...forms, ...extra]
      notes.push(`${phrase} → +[${extra.join(', ')}] (混在読み追加)`)
    }
    readings[phrase] = [...new Set(forms)].join(' ')
  }

  const body = phrases.map((p) => `  ${JSON.stringify(p)}: ${JSON.stringify(readings[p])},`).join('\n')
  const file = `// AUTO-GENERATED by scripts/gen-readings.ts — 手で編集しない。
// 漢字を含む日本語(同義語・ラベル・選択肢の値)のカタカナ読み。ja UI のピッカー内検索で
// 「にんき→人気」のような読み一致に使う。値は空白区切りで、全かな読み＋混在形(かな＋漢字)を
// 含む。再生成: npm run gen:readings
export const READINGS: Record<string, string> = {
${body}
}
`
  const outPath = pathResolve(process.cwd(), 'src/core/readings.generated.ts')
  writeFileSync(outPath, file, 'utf8')

  console.log(`readings.generated.ts を更新: ${phrases.length} 語`)
  console.log(`人手調整 ${notes.length} 件:`)
  for (const line of notes) console.log(`  ${line}`)
})
