/**
 * ja UI のピッカー内検索で「にんき→人気」のような“漢字↔かな読み”一致を効かせるための、
 * 読み辞書の生成スクリプト。漢字を含む日本語テキスト(同義語・ラベル・選択肢の値)を
 * kuromoji でカタカナ読みに変換し、src/core/readings.generated.ts へ書き出す。
 *
 * 実プロダクトの「フリガナ欄」検索と同じく、各語につき“全読み”を1つ持つだけにする
 * (途中まで変換した混在形の列挙はしない=実システムもやらない。IMEが変換しきる前提)。
 *
 * なぜ生成方式か: フィールドは今後増える前提なので、読みを手書きで維持したくない。
 * kuromoji が取り違える数語(例: しきい値→シキイネ)は OVERRIDES で人手上書きする
 * (自動検知はしきれない＝一度は目視が要る、というのが実測での結論)。
 *
 * 実行: npm run gen:readings
 * 生成物はコミットする。コードとズレていないかは check:readings が CI で検査する。
 */
import { writeFileSync } from 'node:fs'
import { resolve as pathResolve } from 'node:path'
import kuromoji from 'kuromoji'
import { collectReadingPhrases } from './readingCorpus'

/**
 * kuromoji が自信満々に取り違える語の人手上書き(かな読み)。値は空白区切りで複数可
 * (例: 板 は「いた」「ばん」両方効かせたい)。ここは目視で育てる小さなリスト。
 */
const OVERRIDES: Record<string, string> = {
  しきい値: 'シキイチ',
  語: 'ゴ',
  板: 'イタ バン',
}

kuromoji.builder({ dicPath: 'node_modules/kuromoji/dict' }).build((err, tokenizer) => {
  if (err) {
    console.error(err)
    process.exit(1)
  }

  const phrases = collectReadingPhrases().sort((a, b) => a.localeCompare(b, 'ja'))
  const readings: Record<string, string> = {}
  const overridden: string[] = []
  for (const phrase of phrases) {
    if (OVERRIDES[phrase]) {
      readings[phrase] = OVERRIDES[phrase]
      overridden.push(`${phrase} → ${OVERRIDES[phrase]} (上書き)`)
      continue
    }
    const tokens = tokenizer.tokenize(phrase)
    readings[phrase] = tokens
      .map((t) => (t.reading && t.reading !== '*' ? t.reading : t.surface_form))
      .join('')
  }

  const body = phrases
    .map((p) => `  ${JSON.stringify(p)}: ${JSON.stringify(readings[p])},`)
    .join('\n')
  const file = `// AUTO-GENERATED by scripts/gen-readings.ts — 手で編集しない。
// 漢字を含む日本語(同義語・ラベル・選択肢の値)のカタカナ読み。ja UI のピッカー内検索で
// 「にんき→人気」のような読み一致に使う。再生成: npm run gen:readings
export const READINGS: Record<string, string> = {
${body}
}
`
  const outPath = pathResolve(process.cwd(), 'src/core/readings.generated.ts')
  writeFileSync(outPath, file, 'utf8')

  console.log(`readings.generated.ts を更新: ${phrases.length} 語`)
  console.log(`人手上書き ${overridden.length} 件:`)
  for (const line of overridden) console.log(`  ${line}`)
})
